FROM node:18-alpine 
# el 18 es la version LTS de node y alpine es una version mas ligera de linux

WORKDIR /app

COPY package.json /

RUN npm install

COPY . /

RUN npm run build

EXPOSE 3000

CMD [ "npm", "start" ]
# todo lo anterior es para crear una imagen de docker que contenga la aplicacion de nextjs